### ISSUE TITLE
(dep):@rollup/plugin-typescript: Could not find module 'tslib'

### ISSUE THREAD

**Issue by codenoobforreal** [alexeagleson/template-react-component-library#1]
yarn run v1.22.17
$ rollup -c

src/index.ts → dist/cjs/index.js, dist/esm/index.js...
[!] (plugin typescript) Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?

install tslib solve this error.
![image](https://user-images.githubusercontent.com/18373253/143869932-9f89a650-5962-404d-8e90-e06bcf5e7581.png)
By the way.very good article.

**Comment by codenoobforreal** [comment]
Also my test failed cuz no "react" and "react-dom" install after peerdenpendcy section.I think it's better to mention it in that section in README.
install all these missing module will solve this kind of error :)
I setup my project following your tutorial step by step instead of folking your repo.so feel free to close it.

**Comment by vgarmes** [comment]
@codenoobforreal I had to install tslib separately, it's actually mentioned in the [plugin install instructions](https://www.npmjs.com/package/@rollup/plugin-typescript)
